### ISSUE TITLE
Dapps in the application menu cannot be used (bug).

### ISSUE THREAD

**Issue by androlo** [eris-ltd/decerver-client#19]
The monkadmin link was not updated after the multi chain stuff was added to thel. There is now a "Monk Admin" in the application menu that does not run. Need to change the way it's loaded (not using package.json etc.) Until that is fixed it can't run.

Until that has been fixed, people can run monk admin by putting the 'monkadmin' folder in the dapp folder as if it was a dapp, but you must add a chain to the package.json etc.

**Comment by androlo** [comment]
It's worth noting that the only way we can make it work automatically is by changing the way we load programs into decerver. There would have to be separate loading processes for different urls etc. It will take some time to fix.

**Comment by compleatang** [comment]
This will get handled by separating the admin UI's out of the DApp pipeline. Closing for now. We can reopen if this starts appearing on other (non-admin dapps).
